backend:
  name: github
  repo: maxireban-bot/funvLORMNU
  branch: main

site_url: https://maxireban-bot.github.io/funvLORMNU
base_url: /funvLORMNU

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Página Principal"
    file: "content/home.json"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
